aws/sagemaker-training-toolkit

.coveragerc_py37
test/functional/test_training_framework.py
test/unit/test_trainer.py
tox.ini

- Add py37 to tox testenv list.
- Fixed errors related to `errno`.
- Ran unit, functional, and integration tests locally using `tox -e py37`.
- The CodeBuild image has not yet been updated with Python 3.7, so the buildspecs have not been modified. A future PR will update the buildspecs to run tox with py37 once the CodeBuild image has been updated.

feature: Add Python 3.7 support

---

setup.py
src/sagemaker_training/encoders.py
src/sagemaker_training/entry_point.py
src/sagemaker_training/functions.py
src/sagemaker_training/mpi.py
src/sagemaker_training/process.py
src/sagemaker_training/runner.py

https://github.com/aws/sagemaker-training-toolkit/issues/60
- There is a known conflict between the built-in `typing` package in Python 3.7 and the backported `typing` package available through PyPI.
- Since this toolkit supports both Python 2.7 and 3.7, the `typing` PyPI dependency and all usage of `typing` have been removed.
Ran tox locally.

fix: Remove typing

---

README.md
test/functional/test_intermediate_output.py

https://github.com/aws/sagemaker-training-toolkit/issues/57
- Edited the Usage section (and corresponding code samples) to be a more concise [how-to guide](https://documentation.divio.com/how-to-guides/).
- Added a link to the example notebooks for users looking for a [tutorial](https://documentation.divio.com/tutorials/).
- Fixed flake8 violation F523.

doc: clean up README usage examples

---

src/sagemaker_training/entry_point.py
src/sagemaker_training/errors.py
src/sagemaker_training/modules.py
test/integration/local/test_dummy.py
test/unit/test_modules.py

- `entry_point.install` installed and ran Python scripts as modules. This caused an issue with the command attempting to execute the incorrect module name.
- This change instead execute Python scripts as normal while adding a command to install from `requirements.txt` to preserve `requirements.txt` support.
Ran unit, functional, and integration tests locally.

fix: run Python script entry point as script and install from requirements.txt

---

src/sagemaker_training/mpi.py
test/unit/test_mpi.py

- An environment variable `AWS_CONTAINER_CREDENTIALS_RELATIVE_URI` set by the Amazon ECS agent was not available in MPI processes.
- This change propagates environment variables to MPI processes to resolve this issue.
- Updated unit tests.
- Tested manually with the current TF 2.2 image.
- These changes will be consumed by [tensorflow-training-toolkit](https://github.com/aws/sagemaker-tensorflow-training-toolkit) and [mxnet-training-toolkit](https://github.com/aws/sagemaker-mxnet-training-toolkit), and automated integration tests will be added in those toolkits due to the dependency on Horovod.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …

feat: persist env vars in /etc/environment for MPI processes

---

src/sagemaker_training/mpi.py
test/unit/test_mpi.py

Use '-bind-to none' flag to improve performance: 
https://horovod.readthedocs.io/en/latest/mpirun.html#run-horovod-with-open-mpi

fix: use '-bind-to none' flag to improve performance. 

---

ENVIRONMENT_VARIABLES.md

`/opt/ml/output/data` isn't mentioned in the [official AWS documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo-envvariables.html) and isn't officially supported by the SageMaker Training platform. Its usage can lead to some unexpected behavior, such as one worker clobbering another in a distributed job.

doc: remove unsupported environment variable

---

test/container/dummy/Dockerfile

From the [AWS Blog](https://aws.amazon.com/blogs/containers/advice-for-customers-dealing-with-docker-hub-rate-limits-and-a-coming-soon-announcement/):
> Docker, Inc. has announced that the Hub service will begin limiting the rate at which images are pulled under their anonymous and free plans. These limits will progressively take effect beginning November 2, 2020.
>
> There are two mitigation approaches we recommend. One, copy public images being used into a private registry such as Amazon Elastic Container Registry (ECR).
This PR copies the `ubuntu:16.04` image into ECR for use as a base image.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! …

infra: use ECR-hosted image for ubuntu:16.04

---

src/sagemaker_training/process.py
test/unit/test_process.py

fix:decode binary stderr string before dumping it out

---

test/container/dummy/Dockerfile

cryptography module has added RUST as its dependency. Upgrading PIP to solve this dependency.
https://github.com/aws/sagemaker-training-toolkit/pull/96
Upgrading PIP to solve this dependency.
cryptography is dependency for [paramiko](https://github.com/aws/sagemaker-training-toolkit/blob/master/setup.py#L41) which is one of the packages needed to build sagemaker-training-toolkit.
By submitting this pull request, I confirm that my contribution is made under the terms …

Update Dockerfile to accomomdate Rust dependency.

---

src/sagemaker_training/smdataparallel.py
test/unit/test_smdataparallel.py

- Enabled the EFA's RDMA functionality for one-sided and two-sided transfer for `ml.p4d.24xlarge` instances.
- Ran the smdataparallel unit test
- Ran the TF2+MNIST smdataparallel jupyter notebook on `p3.16xlarge` and `p4d.24xlarge`, both ran successfully.

feature: smdataparallel enable EFA RDMA flag

---

src/sagemaker_training/smdataparallel.py

- This change provide better error/info messages to the user for socket connection establishment. The change doesn't throw the error message [Traceback] during first or subsequent attempt. It only throws the error message when it tries multiple times for socket connection and times out (default: 1 hour).
**Before**:
- You can see `Cannot connect to host algo-2 at port 22` followed by `paramiko.ssh_exception.NoValidConnectionsError: [Errno None] Unable to connect to port 22 on` on the first try and then `Can connect to host algo-2 at port 22` just after that. The error message confuses the user if the script has failed or not. But the actual reason is that the workers tries to handshake on the first attempt and if it fails, it retries again.
```
2021-04-06 …
```

change: [smdataparallel] better messages to establish the SSH connection between workers

---

src/sagemaker_training/files.py
src/sagemaker_training/process.py
src/sagemaker_training/trainer.py
test/unit/test_process.py

https://github.com/aws/sagemaker-training-toolkit/issues/111
The current state of SM Training toolkit doesn't allow users to write their own custom failure messages in the failure file. This PR fixes this issue by allowing users to do the above. Also, we have made capture error to True by default.
Unit tests and Integration tests passed locally.

Enable custom failure logging

---

setup.py
src/sagemaker_training/mapping.py
src/sagemaker_training/smdataparallel.py
test/unit/test_encoder.py
test/unit/test_mapping.py
test/unit/test_smdataparallel.py
tox.ini

Without the `FI_EFA_USE_DEVICE_RDMA=1`, the NCCL performance is many times slower than with the flag. The flag was removed in https://github.com/aws/sagemaker-training-toolkit/pull/106 because of incompatibility, but should be re-enabled with latest `EFA` with updated `libfabric` and newer `OFI` packages. This PR also updates and fixes `black` lint issues.
Add back `FI_EFA_USE_DEVICE_RDMA=1` flag for faster NCCL performance in `smdataparallel` launcher and unit tests.
feature: add back FI_EFA_USE_DEVICE_RDMA=1 flag, revert 2936f22 
fix: fixed the `black` lint, upgraded black to version 21.3.0
fix: remove u prefix of strings, as python3 defaults to unicode strings
note: EFA is only available on p3dn or p4dn instances
note: EFA version …

add back FI_EFA_USE_DEVICE_RDMA=1 flag, revert 2936f22

---

src/sagemaker_training/process.py
test/unit/test_mpi.py

https://github.com/aws/sagemaker-training-toolkit/issues/119
https://github.com/aws/sagemaker-training-toolkit/issues/115
The process launcher has been moved from `subprocess.Popen` to `asyncio.create_subprocess_shell` starting `v3.9.3`. Due to the behavior of how both of these accept the input command, we need to wrap the shell command in extra pair of quotes to ensure that `bash -c` honors the args passed to the bash script.
But these extra pair of quotes would be a problem for `subprocess.Popen` so had to remove them before launching the process through it.
All unit and formatting test cases passed.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …

fix: missing args when shell script is used

---

src/sagemaker_training/mpi.py
test/unit/test_modules.py

*Description of changes:* Previously the exception_classes was set to None and will caused a issue when use the latest toolkit with previous version of DLC where there's no backend exceptions in smp. Fixing this issue.
Added tests to test_module.py to test the exception class importing. Which contains following circumstance:
1. No SMP exceptions detected 
2. Only torch SMP exception detected
3. Both torch and backend SMP exception detected
As SMP introduced backend exceptions later than torch exceptions, there wouldn't be the case when only backend exceptions detected
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …

Fix none exception class issue for mpi

---

setup.py

Tensorflow requires `protobuf >= 3.9.2, < 3.20` which does not overlap with this package's protobuf requirements. This will lead to a `pip check` failure and an incompatible version of protobuf for TF. 
CI

update: protobuf version to overlap with TF requirements

---

CODE_OF_CONDUCT.md
setup.py
src/sagemaker_training/environment.py
src/sagemaker_training/params.py
src/sagemaker_training/runner.py
src/sagemaker_training/smdataparallel.py
src/sagemaker_training/trainer.py
test/__init__.py
test/unit/test_environment.py
test/unit/test_smdataparallel.py
test/unit/test_trainer.py

feature: Heterogeneous cluster changes

---

src/sagemaker_training/process.py
test/unit/test_process.py

fix: handle utf-8 decoding exceptions while processing std streams

---

src/sagemaker_training/environment.py

* Feature: Allow customers to launch native PTDDP jobs with `nccl` backend using a new distribution value: `{ "pytorchddp": "enabled": "true",  <other options> }}`
* [Design document](https://quip-amazon.com/XqmTAXW29Nua/Improving-Launcher-experience-on-SageMaker)
* In this PR: update distribution_instance_group to copy instance_groups value for pytorchddp as well.
* Connected PRs: 
* https://github.com/aws/sagemaker-pytorch-training-toolkit/pull/236
* https://github.com/aws/sagemaker-python-sdk/pull/3270
* https://github.com/aws/deep-learning-containers/pull/2141
* Unit tests succeed
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate …

change: update distribution_instance_group for pytorch ddp

---

tox.ini

N/A
Hardcoding the older version of the `sagemaker-python-sdk` required additional IAM policies to be able to access the default sagemaker bucket in tests. This change removes the hardcoding so that tests can be run with the most recent `sagemaker` version
Re-confirmed using `tox -e py38 -- test/functional `
- [ x] I have read the [CONTRIBUTING](https://github.com/aws/sagemaker-training-toolkit/blob/master/CONTRIBUTING.md) doc
- [x ] I used the commit message format …

fix: Removed version hardcoding for sagemaker test dependency

---

src/sagemaker_training/smdataparallel.py
test/unit/test_smdataparallel.py

smdataparallel runner hardcodes 8 processes per node since smddp only supported p3 and p4d instance types. Update that to read from env variables instead.
* Unit tests pass
* Custom DLC with these changes successfully runs training for g5 instances

change: update num_processes_per_host for smdataparallel runner

---

src/sagemaker_training/pytorch_xla.py
test/unit/test_pytorch_xla.py

Fix: adding EFA specific setup to distributed training runner for PT-XLA

---

src/sagemaker_training/smdataparallel.py

When user installed a custom PyTorch binary that does not work for SMDDP, we will throw a custom error with detailed reason. Relaxing the Exception type here so training toolkit will not error out. 
Use case:
* User has custom pytorch installed in DLC, and does NOT intend to use SMDDP. Training toolkit should not throw an error when importing SMDDP.
* User has custom pytorch installed in DLC, and enabled SMDDP. Training toolkit will not raise errors, but SMDDP library will raise the error and provide detailed fix method in error message when SMDDP library is  ran and invoked.

relax exception type

---

src/sagemaker_training/__init__.py
src/sagemaker_training/mpi.py
src/sagemaker_training/process.py
src/sagemaker_training/runner.py
src/sagemaker_training/smdataparallel.py
test/unit/test_mpi.py
test/unit/test_smdataparallel.py

ORTE has lost communication with a remote daemon
- Made changes to the non-leader nodes to wait on `orted` process as well as look for the status file sent by the leader node.
- Added `_MPI_ERRORS_` section to the `__init__.py` to capture the MPI related errors in the console.
- Updated logic to capture `psutil.wait_procs` return values and added a callback to invoke on termination.
- updated documentation wherever needed.
- Add EFA specific flags for mpi, sm modelparallalel and dataparallel jobs.
- Updated unit tests
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

fix: Improve worker nodes waiting mechanism in MPI jobs

---

.coveragerc_py36
.coveragerc_py37
.coveragerc_py38
src/sagemaker_training/mapping.py
src/sagemaker_training/torch_distributed.py
test/unit/test_torch_distributed.py

- Added more unit tests for `torch_distributed` launcher.
- Reduce the coverage requirement from 90 to 88 (temporarily) for unblocking contributions (currently the coverage reported with py37 is flaky)
- Addressed `DeprecationWarning` from collections package. 
```
<stdin>:1: DeprecationWarning: Using or importing the ABCs
from 'collections' instead of from 'collections.abc' is deprecated
since Python 3.3, and in 3.10 it will stop working
```
By submitting this pull …

Improve coverage and fix collections DeprecationWarning

---

src/sagemaker_training/__init__.py

Right now the sagemaker training toolkit only log error messages if we found certain error keyword in the logs.
We are missing general exception in the filter to log error messages. 
This PR adds that, right now we are filtering (general python exceptions, MPI errors, SageMaker library specific errors).
In future, we should extend this to custom exceptions and low level/C++ exceptions.

add general exception to filter

---

setup.py

Update highest version of protobuf supported to prevent conflicts with smdebugger's dependency chain.

Upgrade protobuf to prevent conflicts with smdebugger.

---

src/sagemaker_training/smdataparallel.py

We don't need to validate for the presence of liboutofband and libgloo for SMDDP Collectives right now. Removing them from the validation check. 
* Unit tests succeed

change: update libraries for SMDDP collectives validation

---

src/sagemaker_training/mpi.py
src/sagemaker_training/process.py
test/unit/test_process.py

The code in process.py check_error assumes all errors in errors.py as sub classes of _CalledProcessError and reaises that error. Handled SMTrainingCompilerConfigurationError differently as it is not subclass of _CalledProcessError. Reverted the code of registering SMTrainingCompilerConfigurationError with toolkit ([PR](https://github.com/aws/sagemaker-training-toolkit/pull/171/files)) as SMTrainingCompilerConfigurationError can only be raised by toolkit and not the user training script.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …

Fix: to fix SMTrainingCompilerConfigurationError handling in process.py

---

src/sagemaker_training/smdataparallel.py
test/unit/test_smdataparallel.py

We had added support for SMDDP collectives to smdataparallel runner via https://github.com/aws/sagemaker-training-toolkit/pull/162. We merged the toolkit changes, however due to project delays, we didn't merge the related changes in PySDK. Because of this, the warnings we added as a part of this commit are printed in `smdistributed` distribution jobs, and can be distracting/confusing to customers.
Reverting this commit so that the warnings added are not printed in unrelated scenarios.
* Unit tests succeed
* Model training with custom DLC does not print these warnings
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …

fix: Revert SMDDP collectives feature from smdataparallel runner

---

setup.py

tensorflow-gpu 2.12.0rc1 has requirement protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, toolkit now have protobuf 3.20.2.

change: upagrade protobuf version for tensorflow 2.12

---

tox.ini

While we are creating this PR: https://github.com/aws/sagemaker-training-toolkit/pull/178 to fix a connection issue in mpi, we found the newest sagemaker python sdk introduced a credential issue in SMTT pipeline, so we pined the sagemaker version 
to v2.136.0. 
Now, the credential issue is resolved by python SDK PR: https://github.com/aws/sagemaker-python-sdk/pull/3766, and it is merged at latest version v2.145.0.
So we unpin the sagemaker version here now.
By …

unpin sagemaker version as the credential issue fixed

---

src/sagemaker_training/mpi.py

Running FSDP, DS and Megatron DS with smddp backend will be supported on mpi distribution. We will start to track the error telemetry of SMDDP Exception.
Includes the smddp exception in the mpi distribtuion
I have verified that training job works properly with new change.
Here is the sample job output
```
UnexpectedStatusException: Error for Training job vit-fsdp-2023-06-14-22-27-25-988: Failed. Reason: AlgorithmError: SMDDPError:
ExitCode 134
ErrorMessage "raise exceptions.SMDDPError('Error')
smdistributed.dataparallel.exceptions.SMDDPError: Error
Traceback (most recent call last)
File "/opt/conda/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/opt/conda/lib/python3.9/runpy.py", line 87, …
```

Add SM dataparallel exception class in mpi distribution

---

setup.py
src/sagemaker_training/modules.py
test/integration/local/test_dummy.py
test/unit/test_modules.py

*Issue #, if available:* #167
- update modules.install_requirements to check for the presence of codeartifact (CA_* prefixed) environment variable
- if env variable is present, build the authenticated endpoint index url, and add that to the pip install command
- update sagemaker test dependency to support the setting of environment variables and update tox to resolve conflicts with newer sagemaker
- add commented out integ test for installing requirements from codeartifact
- unit tests
- commented out integ test due to infrastructure changes requirements + https://github.com/aws/sagemaker-training-toolkit/pull/187#issuecomment-1630750209
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …

feat: support codeartifact for installing requirements.txt packages

---

src/sagemaker_training/environment.py
src/sagemaker_training/smdataparallel.py
test/unit/test_environment.py

Herring will not be installed on P5 targeted DLCs in the near future, making the smddprun script unavailable.  Thus in this PR, we check whether smddprun is installed and only then append it to the run command in the smdistributed launcher script.  smddprun is only used to set environment variables for Herring jobs so it should not affect ability to run non-Herring jobs with this launcher.  
Verified with local testing that smddprun is correctly appended to the run …

fix: use smddprun only if it is installed

---

setup.py

Pinned versions of boto/botocore does not allow pulling the latest training toolkit version in DLC images

change: update the boto deps to use latest boto

---

buildspec.yml
src/sagemaker_training/modules.py
tox.ini

- Removing unnecessary logging information
- Change ```buildspec.yml``` to not run tests in parallel as it cause flaky .coverage data file issue
Ran ```tox /test/unit``` locally and confirmed all unit tests passed:
```
___________________________________ summary ____________________________________
black-format: commands succeeded
flake8: commands succeeded
pylint: commands succeeded
twine: commands succeeded
py38: commands succeeded
py39: commands succeeded
py310: commands succeeded
congratulations :)
```
Don't have py310 setup in my local environment but it should be fine
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …

chore: removing unnecessary logging information

---

src/sagemaker_training/__init__.py

*Issue #, if available:* 219
*Description of changes:* Add "ml.p5.48xlarge" to SM_EFA_NCCL_INSTANCES. This will automatically set the FI_PROVIDER environment variable to "efa".
*Testing done:* NA

feature: Add p5 as a supported NCCL instance

---

src/sagemaker_training/environment.py
test/unit/test_environment.py

*Issue #, if available:* None
- This is needed to support the upcoming EC2 trn2.48xlarge release. Otherwise, jobs trying to use trn2 will fail (confirmed through testing).
- Checked with Neuron team that the # of Neuron cores in trn2 is 64, so it is hardcoded for now. Neuron team confirmed they will release `lnc_count` which will work for trn2 but to immediately unblock trn2 release, we need this change. We can remove this after their fix is released.
*Testing done:* Updated + added unit tests, `tox test/unit` passed.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …

fix: temporarily hardcode neuron cores for trn2

---

src/sagemaker_training/environment.py

*Issue #:* P174559933
*Description of changes:* Parsing stderr as JSON is a bad practice and caused issue P174559933. This change ensures proper handling of output to prevent similar issues in the future.
*Testing done:* None

fix: avoid parsing stderr as JSON

---

test/unit/test_environment.py

*Issue #, if available:* N/A
- The latest change merged into training toolkit broke the unit tests and thus cannot release successfully. The root cause is that in the `num_neurons` method, previously `stderr` was provided the explicit `subprocess.STDOUT` arg - so we need to update the mock to subprocess.check_output to pass in something for stderr.
Reran the failed test using `tox` with this code change and it passed.
By submitting this pull request, I confirm that my contribution is made …

fix: resolve failing unit test

---

src/sagemaker_training/environment.py

*Issue #, if available:* https://github.com/aws/sagemaker-python-sdk/issues/5012
When using ModelTrainer to run Distributed training with hyperpod recipes sometimes see error like `[Errno 17] File exists: '/opt/ml/code'` due to race condition when multiple processes execute [_create_code_dir](https://github.com/aws/sagemaker-training-toolkit/blob/874f7b055eba3cf3a599b6c5ef74c40396bc9376/src/sagemaker_training/environment.py#L189)
By submitting this pull request, I confirm that my …

fix: account for possible race condition when creating /opt/ml/code

---

src/sagemaker_training/files.py

After spending an afternoon trying to understand why my sourcedir files were not appearing in my custom container using sagemaker-training-toolkit. I realised that the toolkit will not unzip the sourcedir.tar.gz if files are already present in the path. There is not logging to indicate this to an end user which may be helpful for debugging. I have added some logging statements to aid in this.

Adding useful logging info for sourcedir logic
